#!/bin/sh
#------------------------------------------------------------------------------
# CSU - SSH deployment script
# Copyright (c) Jean-Marie RENOUARD 2014 - LightPath
# Contact : Jean-Marie Renouard <jmrenouard at gmail.com>
#
# This program is open source, licensed under the Artistic Licence v2.0.
#
# Artistic Licence 2.0
# Everyone is permitted to copy and distribute verbatim copies of 
# this license document, but changing it is not allowed.
#------------------------------------------------------------------------------
print_usage() {
	echo -e "`basename $0` login public_key_file file_with_list_of_servers"
print_usage() {
        echo -e "`basename $0` chaine_de_connexion"
        echo -e " Deploy public SSH key"
        exit 0
}

[ $# -eq "1" ] && [ $1 != "-h" ] && [ $1 != "--help" ] || print_usage


[ -e "$HOME/.ssh/id_rsa.pub" ] && ssh-copy-id -i $HOME/.ssh/id_rsa.pub $1
[ -e "$HOME/.ssh/id_dsa.pub" ] && ssh-copy-id -i $HOME/.ssh/id_dsa.pub $1
ssh $1
