#!/bin/sh
#------------------------------------------------------------------------------
# CSU - SSH deployment script
# Copyright (c) Jean-Marie RENOUARD 2014 - LightPath
# Contact : Jean-Marie Renouard <jmrenouard at gmail.com>
#
# This program is open source, licensed under the Artistic Licence v2.0.
#
# Artistic Licence 2.0
# Everyone is permitted to copy and distribute verbatim copies of 
# this license document, but changing it is not allowed.
#------------------------------------------------------------------------------
print_usage() {
	echo -e "`basename $0` login public_key_file file_with_list_of_servers"
print_usage() {
        echo -e "`basename $0` ssh_options script"
        echo -e "Remote execute script on server by SSH"
        echo -e "Use ssh keysto automate such operations"
        exit 0
}

[ $# -eq "2" ] && [ $1 != "-h" ] && [ $1 != "--help" ] || print_usage

INTERPRETER=$(head -n 1 $2 | sed -e 's/#!//')

cat $2 | grep -v "#" | ssh -t $1 $INTERPRETER
