#!/bin/bash

USER=${1:-"adcompte"}
LISTE_MACHINE=${2:-"./liste.txt"}

#       CMD=${3:-"/bin/ls -la"}
SRC=${3:-"./bin"}
DEST=${4:-""}
CLEAN_LOG=${5:-"N"}
SILENT=${6:-"N"}
[ -f "$LISTE_MACHINE" ] || echo "$LISTE_MACHINE n'existe pas ..."
[ -f "$LISTE_MACHINE" ] || exit 1

for SERVER in `cat $LISTE_MACHINE`; do
LOG_FILE="/tmp/rsync_$SERVER.log"
LOG_FILE_ERR="/tmp/rsync_$SERVER.err"
[ "$CLEAN_LOG" == "Y" ] && rm -f $LOG_FILE $LOG_FILE_ERR && echo "$LOG_FILE and $LOG_FILE_ERR erased at `date`"
(
 [ "$SILENT" == "Y" ] || echo "#############################################">> $LOG_FILE
 [ "$SILENT" == "Y" ] || echo "$USER@$SERVER $SRC => $DEST  at `date`">> $LOG_FILE
 [ "$SILENT" == "Y" ] || echo "#############################################" >> $LOG_FILE
 [ "$SILENT" == "Y" ] || echo "#############################################">> $LOG_FILE_ERR
 [ "$SILENT" == "Y" ] || echo "$USER@$SERVER $SRC => $DEST at `date`">> $LOG_FILE_ERR
 [ "$SILENT" == "Y" ] || echo "#############################################" >> $LOG_FILE_ERR

 rsync -avz $SRC $USER@$SERVER:$DEST>> $LOG_FILE 2>> $LOG_FILE_ERR

 [ "$SILENT" == "Y" ] || echo "Terminated at `date`">> $LOG_FILE
 [ "$SILENT" == "Y" ] || echo "#############################################">> $LOG_FILE
 [ "$SILENT" == "Y" ] || echo "Terminated at `date`">> $LOG_FILE_ERR
 [ "$SILENT" == "Y" ] || echo "#############################################">> $LOG_FILE_ERR

 echo "$SERVER => $CMD  terminated at `date`"
 )&
done
exit 0
